version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      BACKEND_STORE_URI: postgresql://mlflow:changeme@postgres:5432/mlflow
      ARTIFACT_ROOT: s3://mlflowtuesday-artifacts/artifacts
      AWS_ACCESS_KEY_ID: YCAJEdwnK2r53UPhtCKqbYSRH
      AWS_SECRET_ACCESS_KEY: YCM7DZrwWSxQOzijDub6lKwBVyQ5KZ9POMgDSQU1
    depends_on:
      - postgres

volumes:
  pgdata: 